[package]
name = "siliconmap-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
mysql = "26.0.1"
once_cell = "1.21.3"
rand = "0.8.5"
actix-rt = "2.11.0"
dotenvy = "0.15.7" 
serde = "1.0.228"
argon2 = "0.5"
password-hash = "0.5"